#应用端口配置
server:
  port: 8100
spring:
  jackson:
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  #Spring 开发工具配置
  devtools:
    restart:
      enabled: true
  #数据库配置
  datasource:
    username: root
    password: Z4521663
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    hikari:
      minimum-idle: 2
      maximum-pool-size: 15
  data:
    redis:
      host: localhost
      port: 26378
      client-type: JEDIS
  cache:
    type: REDIS


  freemarker:
    template-loader-path: classpath:/notice-templates
    cache: true
    content-type: text/html; charset=UTF-8

#mybatis-plus配置
mybatis-plus:
  mapperLocations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.ray.dormitory.bean
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    local-cache-scope: session


sys-config:
  templatePath: excel-templates/
  tokenName: Authorization
  tokenTimeout: 1800
  repairerRoleId: 3
  studentRoleId: 4

